def raise_exception():
    raise TypeError("This is a deliberate TypeError")

# Uncomment the following lines if you want to test the function directly
# try:
#     raise_exception()
# except TypeError as te:
#     print("Exception raised")
